apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
  labels: {{- include "demoapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: catalog-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: catalog-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        image.flavor: {{ .Values.flavor }}
    spec:
      {{- with .Values.registry.pullSecret }}
      imagePullSecrets:
        - name: {{ . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: api
          image: {{ include "demoapp.image" (list . .Values.api) | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql+psycopg://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)"
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-postgres
          readinessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /healthz, port: 8000 }
            initialDelaySeconds: 20
          resources: {{- toYaml .Values.api.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
  labels: {{- include "demoapp.labels" . | nindent 4 }}
spec:
  selector:
    app: catalog-api
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 8000
      targetPort: 8000
